version: 1
language: 'en-US'
baseurl: ""
url: "https://multiquine.com"

title: MultiQuine
description: >- # this means to ignore newlines until "baseurl:"
  A digital innovation company with aim of taking game changing ideas and make them reality
logo: assets/images/MultiQuineLogo.png
favicon: assets/images/MultiQuineLogo.png
keywords: [ Computer Softwares ]

twitter: multiquine
facebook: multiquine
linkedin: multiquine
bitbucket: multiquine
instagram: multiquine
